amp: true
anomaly_clean: true
batch_size: 32
cuda: true
data_type: molecule
epochs: 50
freeze_layers: null
freeze_layers_reversed: false
kfold: 3
learning_rate: 0.0001
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics: mae
model_name: unimolv1
num_classes: 19
patience: 5
remove_hs: true
seed: 42
smi_strict: true
smiles_col: SMILES
split: random
split_group_col: scaffold
split_method: 3fold_random
split_seed: 42
target_col_prefix: TARGET
target_cols: TARGET_1,TARGET_2,TARGET_3,TARGET_4,TARGET_5,TARGET_5.1,TARGET_6,TARGET_7,TARGET_8,TARGET_9,TARGET_10,TARGET_11,TARGET_12,TARGET_13,TARGET_14,TARGET_15,TARGET_16,TARGET_17,TARGET_18
target_normalize: auto
task: multilabel_regression
use_amp: true
use_cuda: true
warmup_ratio: 0.03
